Elearn/urls.py
from django.conf import settings
from django.conf.urls import handler403, handler404, handler500
from django.conf.urls.static import static
from django.urls import path, include
from django.views.static import serve

import xadmin
from elearnapp.views import page_not_found, page_error, permission_denied


handler403 = permission_denied
handler404 = page_not_found
handler500 = page_error

urlpatterns = [
    path('admin/', xadmin.site.urls),
    path('', include('elearnapp.urls', namespace='home')),
    path('video/', include('videoapp.urls', namespace='video')),
    path('courseware/', include('coursewareapp.urls', namespace='courseware')),
    path('homework/', include('homeworkapp.urls', namespace='homework')),
    path('exam/', include('examapp.urls', namespace='exam')),
    
    path('mine/', include('userapp.urls', namespace='mine')),
    path('search/', include('haystack.urls')),
]

urlpatterns += static('/media/', document_root=settings.MEDIA_ROOT)  #加上这一行

apps/videoapp/urls.py
from django.urls import path

from videoapp.views import *

app_name = 'videoapp'

urlpatterns = [
    path('', AllVideo.as_view(), name='video'),
    path('player/', Player.as_view(), name='player'),
    path('clicknums/', ClickNums.as_view(), name='clicknums'),
    path('counttime/', Counttime.as_view(), name='counttime'),
    path('uploadcourse/', UploadCourse.as_view(), name='uploadcourse'),
    path('uploadvideo/', UploadVideo.as_view(), name='uploadvideo'),
    path('deletevideo/', DeleteVideo.as_view(), name='deletevideo'),
]

apps/videoapp/models.py
import os
import time
import uuid

from django.db import models

# Create your models here.
# 课程模型
from moviepy.editor import VideoFileClip

from Elearn import settings
from userapp.models import TeacherProfile


class Course(models.Model):
    title = models.CharField(max_length=100, verbose_name='课程标题')
    cover = models.ImageField(upload_to='upload/cover/%Y%m%d', max_length=200, verbose_name='课程封面')
    describe = models.CharField(max_length=300, verbose_name='课程描述', blank=True)
    click_nums = models.IntegerField(default=0, verbose_name="点击量", editable=False)
    add_time = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    teacher = models.ForeignKey(TeacherProfile, on_delete=models.CASCADE, verbose_name='教师')  # 关联课程发布者

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if len(self.cover.name) < 32:
            uuid_str = str(uuid.uuid4()).replace('-', '')
            self.cover.name = uuid_str + os.path.splitext(self.cover.name)[-1]
        super().save()

    def delete(self, using=None, keep_parents=False):
        video = Video.objects.filter(course_id=self.id).all()
        if video is not None:
            for v in video:
                os.remove(os.path.join(file_dir, str(v.file.name)))
            Course.objects.filter(id=self.id).delete()
            os.remove(os.path.join(file_dir, str(self.cover.name)))
        else:
            Course.objects.filter(id=self.id).delete()
            os.remove(os.path.join(file_dir, str(self.cover.name)))

    class Meta:
        db_table = 'courses'
        verbose_name = '课程'
        verbose_name_plural = verbose_name
        ordering = ['click_nums']

    def __str__(self):
        return self.title


# 计算视频时长
file_dir = os.path.join(settings.BASE_DIR, 'media/')


class FileCheck():
    def __init__(self):
        self.file_dir = file_dir

    def get_file_times(self, filename):
        clip = VideoFileClip(filename)
        file_time = FileCheck.timeConvert(self, clip.duration)
        clip.close()
        return file_time

    def timeConvert(self, size):  # 单位换算
        M, H = 60, 60 ** 2
        if size < M:
            return str(size) + u'秒'
        if size < H:
            return u'%s分钟%s秒' % (int(size / M), int(size % M))
        else:
            hour = int(size / H)
            mine = int(size % H / M)
            second = int(size % H % M)
            tim_srt = u'%s小时%s分钟%s秒' % (hour, mine, second)
            return tim_srt


# 视频模型
class Video(models.Model):
    course = models.ForeignKey(Course, verbose_name='课程', on_delete=models.CASCADE)  # 关联课程
    title = models.CharField(max_length=100, verbose_name='视频标题')
    file = models.FileField(upload_to='upload/video/%Y%m%d', max_length=200, verbose_name='视频')
    duration = models.CharField(max_length=30, verbose_name='视频时长', default=0, editable=False)
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        # 对上传视频进行重命名
        if len(self.file.name) < 32:
            uuid_str = str(uuid.uuid4()).replace('-', '')
            self.file.name = uuid_str + os.path.splitext(self.file.name)[-1]
        super().save()
        # 对上传的视频计算时长
        self.duration = FileCheck.get_file_times(self, os.path.join(file_dir, str(self.file.name)))
        super().save()

    def delete(self, using=None, keep_parents=False):
        Video.objects.filter(id=self.id).delete()
        os.remove(os.path.join(file_dir, str(self.file.name)))

    class Meta:
        db_table = 'videos'
        verbose_name = '视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

templates/search/search.html
{% extends 'base.html' %}

{% load static %}

{% block title %}视频{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/elearnapp/index.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/videoapp/video.css' %}"/>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/videoapp/video.js' %}"></script>
{% endblock %}

{% block content %}
    {% if query %}
        <div class="container carousel-outer">
            <div class="row">
                <div class="hot-course-outer">
                    <div class="hot-course-inner">
                        <ul class="course-card-list">
                            {% if page %}
                                {% for result in page.object_list %}
                                    <li class="course-card-item">
                                        <a href="{% url 'video:player' %}?course={{ result.object.id }}&videoid={{ result.object.video_set.first.id }}"
                                           class="item-img-link">
                                            <input hidden="hidden" value="{{ result.object.id }}" name="courseid">
                                            <img src="/static/{{ result.object.cover }}">
                                        </a>
                                        <div class="item-status">
                                            <span>视频数（共{{ result.object.video_set.all.count }}节）</span>
                                        </div>
                                        <h4 class="item-tt">
                                            <a href="{% url 'video:player' %}?course={{ result.object.id }}&videoid={{ result.object.video_set.first.id }}"
                                               class="item-tt-link">{{ result.object.title }}<input hidden="hidden"
                                                                                                    value="{{ course.id }}"
                                                                                                    name="courseid">
                                            </a>
                                        </h4>
                                        <div class="item-line">
                                            <span class="item-click">点击量 : {{ result.object.click_nums }}</span>
                                            <span class="item-source">
                                        <a href="#">{{ result.object.teacher.name }}</a>
                                    </span>
                                        </div>
                                    </li>
                                {% endfor %}
                            {% else %}
                                <div class="reg-log-tip">
                                    <h4>
                                        暂无&nbsp;“<span style="color: #e85308">{{ query }}</span>”&nbsp;相关课程，请您看看其他课程吧！
                                    </h4>
                                </div>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="sort-page">
                    <nav aria-label="Page navigation">
                        <ul class="pagination pagination-lg">
                            {% if page.has_previous %}
                                <li>
                                    <a href="?q={{ query }}&amp;?page={{ page.previous_page_number }}"
                                       aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                            {% else %}
                                <li class="disabled">
                                    <a href="javascript:void(0)" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                            {% endif %}

                            {% for page_number in paginator.page_range %}
                                {% if page_number == paginator.num_pages %}
                                    <li class="page_number active">
                                        <a href="?q={{ query }}&amp;?page={{ paginator.num_pages }}" aria-label="Next"
                                           style="background-color: #12a7ff;border-color: #12a7ff"><span
                                                aria-hidden="true">{{ paginator.num_pages }}</span></a>
                                    </li>
                                {% else %}
                                    <li class="page_number">
                                        <a href="?q={{ query }}&amp;?page={{ paginator.num_pages }}"
                                           aria-label="Next"><span
                                                aria-hidden="true">{{ paginator.num_pages }}</span></a>
                                    </li>
                                {% endif %}
                            {% endfor %}

                            {% if page.has_next %}
                                <li>
                                    <a href="?q={{ query }}&amp;?page={{ page.next_page_number }}"
                                       aria-label="Next"><span
                                            aria-hidden="true">&raquo;</span></a>
                                </li>
                            {% else %}
                                <li class="disabled">
                                    <a href="javascript:void(0)" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}