Elearn/urls.py
from django.conf import settings
from django.conf.urls import handler403, handler404, handler500
from django.conf.urls.static import static
from django.urls import path, include
from django.views.static import serve

import xadmin
from elearnapp.views import page_not_found, page_error, permission_denied


handler403 = permission_denied
handler404 = page_not_found
handler500 = page_error

urlpatterns = [
    path('admin/', xadmin.site.urls),
    path('', include('elearnapp.urls', namespace='home')),
    path('video/', include('videoapp.urls', namespace='video')),
    path('courseware/', include('coursewareapp.urls', namespace='courseware')),
    path('homework/', include('homeworkapp.urls', namespace='homework')),
    path('exam/', include('examapp.urls', namespace='exam')),
    
    path('mine/', include('userapp.urls', namespace='mine')),
    path('search/', include('haystack.urls')),
]

urlpatterns += static('/media/', document_root=settings.MEDIA_ROOT)  #加上这一行

apps/coursewareapp/urls.py
from django.urls import path

from coursewareapp.views import *

app_name = 'coursewareapp'

urlpatterns = [
    path('', CoursewareView.as_view(), name='courseware'),
    path('upload/', UploadFile.as_view(), name='upload'),
    path('download/', DownloadFile.as_view(), name='download'),
    path('downloadnums/', DownloadNums.as_view(), name='download_nums'),
    path('deletecourseware/', DeleteCourseware.as_view(), name='delete_courseware')
]

apps/examapp/urls.py
from django.urls import path

from examapp.views import *

app_name = 'examapp'

urlpatterns = [
    path('', ExamView.as_view(), name='exam'),
    path('details/', ExamDetails.as_view(), name='details'),
    path('judge/', ExamJudge.as_view(), name='judge'),
    path('check/', ExamCheck.as_view(), name='check'),
    path('upload/', UploadExam.as_view(), name='upload'),
    path('addpd/', ExamAddPDQuestion.as_view(), name='addpd'),
    path('addxz/', ExamAddXZQuestion.as_view(), name='addxz'),
    path('addtk/', ExamAddTKQuestion.as_view(), name='addtk'),
    path('addjd/', ExamAddJDQuestion.as_view(), name='addjd'),
    path('release/', ExamRelease.as_view(), name='release'),
    path('correct_student/', ExamReleaseStudent.as_view(), name='correct_student'),
    path('correct/', ExamCorrect.as_view(), name='correct'),
    path('answer/', ExamAnswer.as_view(), name='answer'),
    path('modification/', ExamModification.as_view(), name='modification'),
    path('deletequestion/', ExamDeleteQuestion.as_view(), name='deletequestion'),
    path('deleteexam/', DeleteExam.as_view(), name='deleteexam'),
]

apps/homeworkapp/urls.py
from django.urls import path

from homeworkapp.views import *

app_name = 'homeworkapp'

urlpatterns = [
    path('', HomeworkView.as_view(), name='homework'),
    path('details/', Details.as_view(), name='details'),
    path('judge/', Judge.as_view(), name='judge'),
    path('check/', Check.as_view(), name='check'),
    path('upload/', UploadHomework.as_view(), name='upload'),
    path('addpd/', AddPDQuestion.as_view(), name='addpd'),
    path('addxz/', AddXZQuestion.as_view(), name='addxz'),
    path('addjd/', AddJDQuestion.as_view(), name='addxz'),
    path('release/', Release.as_view(), name='release'),
    path('correct_student/', ReleaseStudent.as_view(), name='correct_student'),
    path('correct/', Correct.as_view(), name='correct'),
    path('answer/', Answer.as_view(), name='answer'),
    path('modification/', Modification.as_view(), name='modification'),
    path('deletequestion/', DeleteQuestion.as_view(), name='deletequestion'),
    path('deletehomework/', DeleteHomework.as_view(), name='deletehomework'),
]

apps/videoapp/urls.py
from django.urls import path

from videoapp.views import *

app_name = 'videoapp'

urlpatterns = [
    path('', AllVideo.as_view(), name='video'),
    path('player/', Player.as_view(), name='player'),
    path('clicknums/', ClickNums.as_view(), name='clicknums'),
    path('counttime/', Counttime.as_view(), name='counttime'),
    path('uploadcourse/', UploadCourse.as_view(), name='uploadcourse'),
    path('uploadvideo/', UploadVideo.as_view(), name='uploadvideo'),
    path('deletevideo/', DeleteVideo.as_view(), name='deletevideo'),
]

ext_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/courseware.html
{% extends 'base.html' %}

{% load static %}

{% block title %}公告{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/coursewareapp/courseware.css' %}">
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/coursewareapp/courseware.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="download-courseware">
                <ul>
                    <li>
                        <div><h5>公告名</h5></div>
                        <div><h5>教师</h5></div>
                        <div><h5>大小</h5></div>
                        <div><h5>上传时间</h5></div>
                        <div><h5>下载次数</h5></div>
                    </li>
                    <hr class="courseware-hr"/>
                </ul>
                <ul>
                    {% for courseware in page %}
                        <li>
                            <div class="courseware-name">
                                <a href="{% url 'courseware:download' %}?file={{ courseware.id }}" title="点击下载">
                                    {{ courseware.name }}
                                    {% csrf_token %}
                                    <input hidden="hidden" name="courseware-id" value="{{ courseware.id }}">
                                </a>
                            </div>
                            <div class="courseware-teacher-name">
                                <span>{{ courseware.teacher.name }}</span>
                            </div>
                            <div class="courseware-size">
                                <span>{{ courseware.size }}</span>
                            </div>
                            <div class="courseware-time">
                                <span>{{ courseware.add_time }}</span>
                            </div>
                            <div class="courseware-download-nums">
                                <span>{{ courseware.download_nums }}</span>
                            </div>
                            {% if request.session.user.identity == 'teacher' %}
                                <div>
                                    {% csrf_token %}
                                    <button class="btn btn-sm delete-courseware" value="{{ courseware.id }}">删除</button>
                                </div>
                            {% endif %}
                        </li>
                        <hr class="courseware-hr"/>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="courseware-pagination">
                {% if page.has_previous %}
                    <a href="{% url 'courseware:courseware' %}?page={{ 1 }}">首页</a>
                    <a href="{% url 'courseware:courseware' %}?page={{ page.previous_page_number }}">上一页</a>
                {% else %}
                    <a style="color: #333333">首页</a>
                    <a style="color: #333333">上一页</a>
                {% endif %}

                {% if page.has_next %}
                    <a href="{% url 'courseware:courseware' %}?page={{ page.next_page_number }}">下一页</a>
                    <a href="{% url 'courseware:courseware' %}?page={{ paginator.num_pages }}">末页</a>
                {% else %}
                    <a style="color: #333333">下一页</a>
                    <a style="color: #333333">末页</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/exam.html
{% extends 'base.html' %}

{% load static %}

{% block title %}考试{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/examapp/exam.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="exam">
                <ul>
                    <li>
                        <div><h5>考试名称</h5></div>
                        <div><h5>教师</h5></div>
                        <div><h5>说明</h5></div>
                        <div><h5>发布时间</h5></div>
                        <div><h5>作答人数</h5></div>
                    </li>
                    <hr class="exam-hr"/>
                </ul>
                <ul>
                    {% for exam in all_exam %}
                        <li>
                            <div class="exam-name">
                                <a href="{% url 'exam:details' %}?list={{ exam.id }}">{{ exam.name }}</a>
                            </div>
                            <div class="exam-teacher-name">
                                <span>{{ exam.teacher.name }}</span>
                            </div>
                            <div class="exam-desc">
                                <span>{{ exam.describe }}</span>
                            </div>
                            <div class="exam-time">
                                <span>
                                    {{ exam.add_time }}
                                </span>
                            </div>
                            <div>
                                <span>
                                    {{ exam.answer_nums }}
                                </span>
                            </div>
                        </li>
                        <hr class="exam-hr"/>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="exam-pagination">
                {% if page.has_previous %}
                    <a href="{% url 'exam:exam' %}?page={{ 1 }}">首页</a>
                    <a href="{% url 'exam:exam' %}?page={{ page.previous_page_number }}">上一页</a>
                {% else %}
                    <a style="color: #333333">首页</a>
                    <a style="color: #333333">上一页</a>
                {% endif %}

                {% if page.has_next %}
                    <a href="{% url 'exam:exam' %}?page={{ page.next_page_number }}">下一页</a>
                    <a href="{% url 'exam:exam' %}?page={{ paginator.num_pages }}">末页</a>
                {% else %}
                    <a style="color: #333333">下一页</a>
                    <a style="color: #333333">末页</a>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

templates/exam_correct.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/examapp/exam.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="correct-exam">
                <form action="{% url 'exam:correct' %}" method="post">
                    {% csrf_token %}
                    <input name="studentid" value="{{ student_id }}" hidden="hidden">
                    <ul>
                        {% for pd in pd_list %}
                            {% if forloop.first %}
                                <input name="examid" value="{{ pd.exam_id }}" hidden="hidden">
                                {# 考试id #}
                            {% endif %}
                            <li>
                                <h5>{{ forloop.counter }}.&nbsp;{{ pd.question }}</h5>
                                <p>学生答案：{{ pd.answer }}</p>
                            </li>

                        {% endfor %}
                        <hr/>

                        {% for xz in xz_list %}
                            <li>
                                <h5>{{ forloop.counter }}.&nbsp;{{ xz.question }}</h5>
                                <p>A.&nbsp;{{ xz.question.choice_a }}</p>
                                <p>B.&nbsp;{{ xz.question.choice_b }}</p>
                                <p>C.&nbsp;{{ xz.question.choice_c }}</p>
                                <p>D.&nbsp;{{ xz.question.choice_d }}</p>
                                <p>学生答案：{{ xz.answer }}</p>
                            </li>

                        {% endfor %}
                        <hr/>

                        {% for tk in tk_list %}
                            <li>
                                <h5>{{ forloop.counter }}.&nbsp;{{ tk.question }}</h5>
                                <p>学生答案：{{ tk.answer }}</p>
                                <input name="{{ tk.question_id }}" value="{{ tk.question_id }}" hidden="hidden">
                                <input name="score{{ tk.question_id }}" placeholder="请输入分数">
                            </li>
                        {% endfor %}
                        <hr/>

                        {% for jd in jd_list %}
                            <li>
                                <h5>{{ forloop.counter }}.&nbsp;{{ jd.question }}</h5>
                                <p>学生答案：{{ jd.answer }}</p>
                                <input name="{{ jd.question_id }}" value="{{ jd.question_id }}" hidden="hidden">
                                <input name="score{{ jd.question_id }}" placeholder="请输入分数">
                            </li>
                        {% endfor %}
                    </ul>
                    <input type="submit" value="提交">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/exam_details.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/examapp/exam.css' %}">
{% endblock %}

{% block js %}
    <script type="text/javascript">
        window.onload = function check() {
            $.ajax({
                url: "/exam/check/",
                type: "get",
                data: {
                    "h": $("input[name='h']").val(),
                },
                success: function (data) {
                    if (data["status"] === true) {
                        $(".exam-submit").attr('disabled', 'disabled');
                        {# 考试已提交，禁止再次提交 #}
                        $(".exam-submit-tip").removeAttr('hidden');
                        {# 考试已提交提示 #}
                    } else if (data["status"] === false) {
                        $(".exam-submit").removeAttr('disabled');
                        $(".exam-submit-tip").attr('hidden', 'hidden')
                    }
                }
            });
        };
    </script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="question">
                <form id="{{ question.id }}" method="post" action="{% url 'exam:judge' %}">
                    {% csrf_token %}
                    <input hidden name="h" value="{{ h_id }}"> {# 考试id #}
                    <ul>
                        <h5>一、判断题</h5>
                        {% for question in pd_list %}
                            <li>
                                <h5>{{ forloop.counter }}.&nbsp;{{ question.context }}</h5>
                                <input type="hidden" value="{{ question.id }}"/>
                                <input name="{{ question.id }}" type="radio" value="true"/>&nbsp;正确
                                <br/>
                                <input name="{{ question.id }}" type="radio" value="false"/>&nbsp;错误
                                <br/>
                            </li>
                        {% endfor %}
                    </ul>
                    <br/>
                    <ul>
                        <h5>二、选择题</h5>
                        {% for question in xz_list %}
                            <li>
                                <h5>{{ forloop.counter }}.&nbsp;{{ question.context }}</h5>
                                <input type="hidden" value="{{ question.id }}"/>
                                <input name="{{ question.id }}" type="radio" value="A"/>&nbsp;A.{{ question.choice_a }}
                                <br/>
                                <input name="{{ question.id }}" type="radio" value="B"/>&nbsp;B.{{ question.choice_b }}
                                <br/>
                                <input name="{{ question.id }}" type="radio" value="C"/>&nbsp;C.{{ question.choice_c }}
                                <br/>
                                <input name="{{ question.id }}" type="radio" value="D"/>&nbsp;D.{{ question.choice_d }}
                                <br/>
                            </li>
                        {% endfor %}
                    </ul>
                    <br/>

                    <ul>
                        <h5>三、填空题</h5>
                        {% for question in tk_list %}
                            <li>
                                <h5>{{ forloop.counter }}.&nbsp;{{ question.context }}</h5>
                                <input type="hidden" value="{{ question.id }}"/>
                                <textarea name="{{ question.id }}" placeholder="在此作答" class="form-control"></textarea>
                                <br/>
                            </li>
                        {% endfor %}
                    </ul>
                    <br/>

                    <ul>
                        <h5>四、简答题</h5>
                        {% for question in jd_list %}
                            <li>
                                <h5>{{ forloop.counter }}.&nbsp;{{ question.context }}</h5>
                                <input type="hidden" value="{{ question.id }}"/>
                                <textarea name="{{ question.id }}" placeholder="在此作答" class="form-control"></textarea>
                                <br/>
                            </li>
                        {% endfor %}
                    </ul>
                    <input type="submit" class="btn btn-primary exam-submit" value="确认提交">&nbsp;
                    <span class="exam-submit-tip" hidden="hidden" style="color: red">你已作答</span>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/homework.html
{% extends 'base.html' %}

{% load static %}

{% block title %}作业{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/homeworkapp/homewrok.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="homework">
                <ul>
                    <li>
                        <div><h5>作业名</h5></div>
                        <div><h5>教师</h5></div>
                        <div><h5>说明</h5></div>
                        <div><h5>发布时间</h5></div>
                        <div><h5>作答人数</h5></div>
                    </li>
                    <hr class="homework-hr"/>
                </ul>
                <ul>
                    {% for homework in all_homework %}
                        <li>
                            <div class="homework-name">
                                <a href="{% url 'homework:details' %}?list={{ homework.id }}">{{ homework.name }}</a>
                            </div>
                            <div class="homework-teacher-name">
                                <span>{{ homework.teacher.name }}</span>
                            </div>
                            <div class="homework-desc">
                                <span>{{ homework.describe }}</span>
                            </div>
                            <div class="homework-time">
                                <span>
                                    {{ homework.add_time }}
                                </span>
                            </div>
                            <div>
                                <span>
                                    {{ homework.answer_nums }}
                                </span>
                            </div>
                        </li>
                        <hr class="homework-hr"/>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="homework-pagination">
                {% if page.has_previous %}
                    <a href="{% url 'homework:homework' %}?page={{ 1 }}">首页</a>
                    <a href="{% url 'homework:homework' %}?page={{ page.previous_page_number }}">上一页</a>
                {% else %}
                    <a style="color: #333333">首页</a>
                    <a style="color: #333333">上一页</a>
                {% endif %}

                {% if page.has_next %}
                    <a href="{% url 'homework:homework' %}?page={{ page.next_page_number }}">下一页</a>
                    <a href="{% url 'homework:homework' %}?page={{ paginator.num_pages }}">末页</a>
                {% else %}
                    <a style="color: #333333">下一页</a>
                    <a style="color: #333333">末页</a>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}